import React, { Component } from 'react';
import { connect } from 'react-redux';
import PropTypes from 'prop-types';
import _ from 'lodash';
import { destroySession,
  sessionFromToken, sessionFromTokenSuccess, sessionFromTokenFailure } from '../../actions/';

export default function (ComposedComponent) {
  class Authentication extends Component {
    async loadUserFromToken() {
      let token = localStorage.getItem('token');

      if(_.isEmpty(token)) {//if there is no token, dont bother
        return this.props.destroySession();
      }

     //fetch user from token (if server deems it's valid token)
      const response = await this.props.sessionFromToken(token);
      if (!response.error) {
        //reset token (possibly new token that was regenerated by the server)
        localStorage.setItem('token', response.data.token);
        this.props.sessionFromTokenSuccess(response.data.user)
      } else {
        localStorage.removeItem('token');//remove token from storage
        this.props.sessionFromTokenFailure(response)
          // .then((response) => {
          //   this.props.history.push('/login');
          // });
      }
    }

    resetMe() {
      localStorage.removeItem('token'); //remove token from storage
      this.props.destroySession();
    }

    componentWillMount() {
      this.loadUserFromToken();
    }

    componentWillReceiveProps(nextProps) {
      const { history } = this.props;
      if (_.isEmpty(localStorage.getItem('token'))) {
        history.push('/login')
      }
    }
    PropTypes = {
      router: PropTypes.object,
    }

    render() {
      return <ComposedComponent {...this.props} />;
    }
  }

  function mapStateToProps(state) {
    return { user: state.session.user };
  }

  return connect(mapStateToProps, { sessionFromToken, sessionFromTokenSuccess, sessionFromTokenFailure, destroySession})(Authentication);
}