# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       # - image: circleci/ruby:2.4.1-node-browsers
      # - image: buildpack-deps:trusty # primary container
        # environment:
        #   ENV: CI
      - image: circleci/ruby:2.4.1-node-browsers
      - image: mongo:3.4.6
        command: [--smallfiles]
      # - image: selenium/standalone-firefox:latest
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo/api

    steps:
      - checkout:
          path: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: Install latest version of GeckoDriver
          command: |
            curl -L https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz | tar xz
            chmod +x geckodriver
            sudo mv geckodriver /usr/bin/
      # Run XVFB for features specs (firefox)
      # - run:
      #     name: Running X virtual framebuffer
      #     command: Xvfb -ac :99 -screen 0 1280x1024x16 +extension RANDR
      #     background: true

      # run tests!
      # "spec/**/*_spec.rb" 
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_feature.rb"| circleci tests split --split-by=timings)"
            DISPLAY=:99
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            -- $(sed -e 's/\n/\\n/' -e 's/ /\ /' <<< "${TEST_FILES}")

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results