# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  stripe:
    redirect_url: "http://localhost:3001/houses/token"

test:
  stripe:
    redirect_url: "http://127.0.0.1:4242/houses/token"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  stripe:
    redirect_url: "https://api.hackerhouse.paris/houses/token"