source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use sqlite3 as the database for Active Record
# gem 'sqlite3'
# Use mongoid as the ORM database
gem 'mongoid', '6.0.2'
gem 'mongoid_rails_migrations'

# Use Puma as the app server
gem 'puma', '~> 3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# Use Grape as REST API micro-framework
gem 'grape'

# User Active Model Serializer as formatter
gem 'grape-active_model_serializers'
# Use Grape Middle logger to log requests / exceptions and more
gem 'grape-middleware-logger'

# Use Pundit as Authorization library
gem 'pundit'

# Use Stripe as Payment platform
gem 'stripe'

# Use standardized way to build Service Objects
gem 'simple_command'

# Use JWT  as Authentication
gem 'jwt'

# Use Bcrypt as Password encryption
gem 'bcrypt'

# Use Rack Cors to allow web applications to make cross domain AJAX calls
gem 'rack-cors', require: 'rack/cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry'
  gem 'rspec-rails'
end

group :test do
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'rspec-collection_matchers'
  gem 'stripe-ruby-mock', '~> 2.4.1', require: 'stripe_mock'
  gem 'selenium-webdriver'
  gem 'timecop'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
