source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'
# Use sqlite3 as the database for Active Record
# gem 'sqlite3'
# Use mongoid as the ORM database
gem 'mongoid', '6.0.2'
gem 'mongoid_rails_migrations'

# Use Puma as the app server
gem 'puma', '~> 3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'
gem 'faraday'
# Use Oauth2 as wrapper for the OAuth 2.0 specification
gem 'oauth2'

# Use Grape as REST API micro-framework
gem 'grape'

# User Active Model Serializer as formatter
gem 'grape-active_model_serializers'
# Use Grape Middle logger to log requests / exceptions and more
gem 'grape-middleware-logger'

# Use httpclient as http library
gem 'httpclient'

# Use Pundit as Authorization library
gem 'pundit'

# Use Stripe as Payment platform
gem 'stripe'

# Use standardized way to build Service Objects
gem 'simple_command'

# Use JWT  as Authentication
gem 'jwt'

# Use Bcrypt as Password encryption
gem 'bcrypt'

# Use Rack Cors to allow web applications to make cross domain AJAX calls
gem 'rack-cors', require: 'rack/cors'

gem 'actionmailer_inline_css'

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.1.0", require: false

# Ruby bindings for the Intercom API
gem 'intercom'

# A Ruby and command-line client for the Slack Web and Real Time Messaging APIs.
gem 'slack-ruby-client'

# Sentry is cross-platform application monitoring, with a focus on error reporting.
gem "sentry-raven", require: 'sentry-raven-without-integrations'


# Ruby file uploads
# Mongoid extension for Refile.
gem 'refile', github: 'refile/refile', require: 'refile/rails'
gem "refile-mini_magick"
gem 'refile-mongoid', github: 'DimaSamodurov/refile-mongoid'
gem 'refile-s3', github: 'refile/refile-s3'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'mongoid_colored_logger', github: 'romanbsd/mongoid_colored_logger'
  gem 'pry-rails'
end

group :development do
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rspec-rails'
end

group :test do
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'rspec-collection_matchers'
  # need to use master because 2.5.0 does not work with subscription#items https://github.com/rebelidealist/stripe-ruby-mock/issues/464
  gem 'stripe-ruby-mock', require: 'stripe_mock', github: 'sbounmy/stripe-ruby-mock', branch: 'justin808/update-api-to-2018-02-6'
  gem 'selenium-webdriver'
  gem 'timecop'

  # RSpec results formatted as JUnit XML that your CI can read
  gem "rspec_junit_formatter"
end

group :production do
  gem 'postmark-rails'
end
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
